### PR TITLE
Decrease the participant appear time

### PR DESCRIPTION
**Pull request by mustafaboleken**
https://github.com/ant-media/conference-call-application/issues/141

### CODE REVIEW

**Review by mekya — CHANGES_REQUESTED** [review]
Decreasing roomInfo interval is not a very good idea to just let the user see other guys when he login. 
There are a couple of options 
- Just get the room info first when user first enters the room
- The better solution is "JoinedRoom" response includes the streams in the room so if there is anyone in the room, you can start playing directly.

**Comment by mustafaboleken** [comment]
> Decreasing roomInfo interval is not a very good idea to just let the user see other guys when he login. There are a couple of options
> 
>     * Just get the room info first when user first enters the room
> 
>     * The better solution is "JoinedRoom" response includes the streams in the room so if there is anyone in the room, you can start playing directly.

If we talked about newly joined person, these options are valid. When I read the issue, I though we just need to decrease time for everybody. I mean old participants should see new comers early too.

**Comment by mekya** [comment]
Just make it simple. Just let first comers see the every guys in the room as soon as possible. Not after 5 seconds. 

For old participants, it takes about max 5 seconds to see the new comer.  So it's not a big deal at this stage.

**Comment by mustafaboleken** [comment]
Fixed on https://github.com/ant-media/conference-call-application/pull/157

**Pull request closed without merging**
