### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by burak-58**
some fixes and debugging improvements

### CODE REVIEW

**Comment by burak-58** [comment]
Fixes: https://github.com/ant-media/conference-call-application/issues/5

**Comment by burak-58** [comment]
https://github.com/ant-media/conference-call-application/issues/6

**Comment by mekya** [comment]
Please just give some more tangible things for the title? `Improvements` seems not good.

**Review by mustafaboleken — APPROVED** [review]
lgtm

**Pull request merged**
